spring.application.name=HealthManagementSystem

# application-h2.properties (for H2 dev profile)
spring.datasource.url=jdbc:h2:mem:hmsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Enable H2 console (Web UI)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Server Post
server.port=8080



##### NOTES ######
#   jdbc:h2:mem:hmsdb ? in-memory DB named hmsdb.
#   DB_CLOSE_DELAY=-1 keeps DB alive while JVM runs.
#   ddl-auto=update lets JPA create/update tables for dev.